#!/bin/sh


# Include the configuration file #
source ~/.wolrc

# Update ARP Table #
arp > /dev/null

# Look for your MAC address, and make it look nice #
if cat /proc/net/arp | grep $MAC > /dev/null
then
  echo -e "\nsean's online\n"
  cat /proc/net/arp | colrm 59 | colrm 18 41 | grep -e $MAC -e 'HW address'
  echo
else
    echo -e "\nsean's not online\n"
fi
